### ISSUE TITLE
McMMO / MPet "report to paper"

### ISSUE THREAD

**Issue by pricelessdev** [PaperMC/papermc.io#31]
I have MythicMobs and Miniatures Pets where I spawn a pet as a MythicMob with an AI, and everything should work good but it despawns right after spawned and throws that error in console.

`[10:31:48 ERROR]: [global] TIMING_STACK_CORRUPTION - Report this to Paper! This is a potential bug in Paper (TimingIdentifier{id=Minecraft:## tickEntity - net.minecraft.server.v1_14_R1.EntityChicken} did not stopTiming)
java.lang.Throwable: null
        at co.aikar.timings.TimingHandler.popTimingStack(TimingHandler.java:135) ~[patched_1.14.4.jar:git-Paper-225]
        at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:117) ~[patched_1.14.4.jar:git-Paper-225]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:486) ~[patched_1.14.4.jar:git-Paper-225]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1231) ~[patched_1.14.4.jar:git-Paper-225]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-225]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-225]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-225]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]`

**Comment by electronicboy** [comment]
More than likely, there was another exception thrown at the same time as
that one, that is the important one, the paper one is just timings being
upset due to the exception causing a timing handler to not be stopped
properly

**Comment by zachbr** [comment]
This is the website repo, not the repo for the server software. Please either seek support from the Community (with the full logs) https://papermc.io/community, or create an issue in the proper repo at [PaperMC/Paper](https://github.com/PaperMC/Paper) and fill out all the requested information.
